### ISSUE TITLE
indels incorrectly removed in import_indels()

### ISSUE THREAD

**Issue by ChristofferFlensburg** [annaquaglieri16/varikondo#1]
So the last line of

```
  indels <- indels %>%
    dplyr::filter(nchar(alt) > minLength) %>%
    tidyr::separate(SampleName,into=c("OurPID","Time","Status","Repl.within","batch","Outcome"),remove = FALSE,sep="[.]") %>%
    dplyr::filter(OurPID %in% patientID) %>% # restrict analysis to OurPID
    dplyr::filter(SYMBOL %in% studyGenes) %>% # restrict analysis to specific genes
    dplyr::filter(qual > minQual) %>%
    dplyr::filter(IMPACT %in% c("HIGH", 'MODERATE')) %>%
    dplyr::group_by(Location,ref,alt) %>% # for every Location called only keep the highest rank
    dplyr::filter(order(IMPACT_rank) == order(IMPACT_rank)[which.min(order(IMPACT_rank))])
```

(that I added, of course) is bugged. It leaves only the row with the most severe IMPACT for each variant and deletes all other entries. Unfortunately this also means that it removes the same variant with the same IMPACT in other samples of the sample patient, effectively stopping us from having any variant present in multiple samples...

What we want to do here, is to pick variants that pass the filters in `qual` and `IMPACT` for any sample of a patientID, and keep that variant for all samples of that patient, even if the calls in other samples don't pass filters. Better to have a low quality VAF than defaulting to 0 VAF. But only keep the annotation of the variant with the highest IMPACT.

I'm not sure how to best do that in long tidy format though, can you help Anna??

**Comment by ChristofferFlensburg** [comment]
I tried to fix this with the commit yesterday by adding 👍. Some things work better, but not sure if it's all good. Still seems like there are discrepancies between replicates. Might still be bugs, and there might be the problem with the same indel being called as slightly different variants in the different samples, and then they don't get paired up properly... :/

**Comment by ChristofferFlensburg** [comment]
Ok, next step in the indel saga.

I had a look at an indel called in only one of the replicates. It had very low coverage: 2 reads, both indels. I think we have a problem with thresholds, where one replicate will barely call a variant, the other will barely not.

I think I'll add in a cut in read depth, only including things with at least 10 reads coverage or so, but it doesn't really remove the problem as variants with 11 reads in one replicate and 9 in the other will still have this issue.

Maybe we do a first check on variants in any sample of a patient with a bit stricter cuts (coverage, read quality, VAF), and we then search for any information on those variants in the rest of the samples of the patient. Is there a neat way to do that in tidy? Otherwise I'll do some ugly hack in base. :D We do that a bit already with the later filters on maximum VAF... Worst case I could just extend that part I guess.

**Comment by annaquaglieri16** [comment]
I see... so if I understand well, for one patient, some indels are not called at all while in another sample they are marginally called? So here the logic would be that we want to see only what was called with some confidence in one of the samples? But wouldn't we incur into the same issue? What I mean is that if we set a higher filter, then if a variant anyway had very low depth in one sample, still this will appear as a VAF=zero into our plot? 

What about working with the size of the line to include the alternative depth information? extra level of crowding? 

In any case I wrote these few lines of code with sample data that maybe do what you were saying?

```{r}
# indels 
library(tidyverse)

# Example data
# In the example below:
# I added a key for an indel including chr_pos_alt allele
# I added a variant ID just for this example to quickly inspect what variants should be left in 
# Below only variants A and B should be left in since C does not pass the filters in any sample
# The remission sample is never called by the caller


########################
## Create sample data
########################

# example indels
indels <- data.frame(PID = rep("P1",9),
                     Time = c(rep("Screen",3),rep("Cyc1",3),rep("Cyc2",3)),
                     Location = c("chr1_10","chr1_20","chr2_30","chr1_10","chr1_20","chr2_30","chr1_10","chr1_20","chr2_30"),
                     alt = c("ACT","ACGTCG","AGG","ACT","ACGTCG","AGG","ACT","ACGTCG","AGG"),
                     ref_depth = c(12,11,9,9,12,8,13,14,8),
                     vaf = rep(0.7,9)) %>% 
  mutate(variant_ID = c("A","B","C","A","B","C","A","B","C")) %>%
  unite(key, Location,alt,sep="_",remove=FALSE) 

# example clinical
clinical <- data.frame(PID = rep("P1",4),
                       Time = c("Screen","Rem","Cyc1","Cyc2"))


#############################################
## Manipulate to get it int he right format
##########################################

# Unique indels found
unique_indels <- unique(indels[,c("Location","key","alt","variant_ID")])
clinical_indels_empty <- merge(clinical ,unique_indels,all=TRUE)
# Fill NA's
clinical_indels_fill <- merge(clinical_indels_empty,indels,all=TRUE) %>% 
  mutate(ref_depth = ifelse(is.na(ref_depth),0,ref_depth),
         vaf = ifelse(is.na(vaf),0,vaf))

# Filter and re-add later
indels_keep <- clinical_indels_fill %>% filter(ref_depth >= 10) 
indels_leave <- clinical_indels_fill %>% filter(ref_depth < 10) 

add_left_indels <-  bind_rows(indels_keep,subset(indels_leave,key %in% indels_keep$key)) %>% arrange(Time, variant_ID)

#################################################################
# convert into wide format for the type of plotting thar you do

add_left_indels_wide <- add_left_indels %>% 
  select(-ref_depth) %>%  # need to remove all the columns that have different values across samples
  tidyr::spread(key = Time,value=vaf,fill=NA)

```

Is that right?

**Comment by annaquaglieri16** [comment]
I am going to add the code above to the import_indels function.

**Comment by annaquaglieri16** [comment]
I added the code above but we might want to discuss a few things:

* using VAF and tot_depth to filter as mentioned in issue #10 
* tidy/untidy outputs
