### ISSUE TITLE
mutationSummary SNVs report chromosome not matching

### ISSUE THREAD

**Issue by annaquaglieri16** [annaquaglieri16/varikondo#11]
Is the following ok:

```{r}

                              x1         x2                  call stories.D1.Cyc3.Rel.R1.B1.Rel stories.D1.Screen.Diag.R1.B1.Rel
2105057471+TCCGTCTCCT 2105057471 2105057471 2105057471+TCCGTCTCCT                     0.3375502                        0.0000000
chrX.A                2875277845 3031029705                     A                     0.7412836                        0.6813482
                      stories.D1.Cyc1.Rem.R1.B2.Rel stories.D1.Screen.Diag.R1.B2.Rel errors.D1.Cyc3.Rel.R1.B1.Rel
2105057471+TCCGTCTCCT                     0.0000000                        0.0000000                   0.05210447
chrX.A                                    0.4639560                        0.5501232                   0.14463954
                      errors.D1.Screen.Diag.R1.B1.Rel errors.D1.Cyc1.Rem.R1.B2.Rel errors.D1.Screen.Diag.R1.B2.Rel   GoI
2105057471+TCCGTCTCCT                      0.01036135                   0.04028248                      0.03689244  FLT3
chrX.A                                     0.14788838                   0.16543493                      0.16067887 STAG2
                                     label severity chr    start       end
2105057471+TCCGTCTCCT FLT3 (13) frameshift        5  13 20291170  20291170
chrX.A                        156Mbp A (X)        0  22 45549125 149996419

```

The second rowname is chrX but then in chr column it says 22. Is that ok?

**Comment by ChristofferFlensburg** [comment]
No, that's not ok. That's a sign that one of the is calculated with the wrong genome. The rowname is probably the accurate one, as it's from the superFreq run that should be internally consistent. The chr column is something added on afterwards. That x1 maps to chrX in hg38 (which is what we are using right?), and to chr22 in hg19, which I might've accidentally done at one point.

**Comment by annaquaglieri16** [comment]
So, are you able to locate where the error might have occured? Is it related to some inputs or is it done internally within `superFreq`?

**Comment by ChristofferFlensburg** [comment]
I think we identified and fixed the bug in the import script at some point, but seems like it's still present in some import scripts. I'll see if I can fix it and do a pull request linked to this issue. Advanced github usage for me! :o

**Comment by ChristofferFlensburg** [comment]
No idea if I'm doing this right. 🤷‍♂️

**Comment by annaquaglieri16** [comment]
ahahaha I am not sure! That's too advanced for me as well :D :D

**Comment by ChristofferFlensburg** [comment]
Can you accept the pull request somehow, to include it your script?

**Comment by annaquaglieri16** [comment]
I am trying to understand what I have to do --- not sure I do! Did I do soemthing? What exactly shall I accept? Do you think I should get a notification?

**Comment by ChristofferFlensburg** [comment]
I sent a pull request suggesting changes to the code that hopefully fixes this issue, that is linked above. As owner of the repo, you need to accept the pull request for the code to be part of the package. Or that is how I think it works. :P

**Comment by annaquaglieri16** [comment]
I think I did it :D :D 💯 🥇 First pull request with merging conflicts including different function names and different name of the package 👍

**Comment by ChristofferFlensburg** [comment]
Wait different name?
I just added an option at a few lines... But maybe you changed things in the meanwhile?

Well done though! 🎉

**Comment by annaquaglieri16** [comment]
I think on Sunday or late last week I changed `extract_goi_superfre.R` to `import_goi_superfreq` to be consistent with the other `import` function...

Also I had just realised this morning that initially I spellt  import_goi_sup**ef**req so I changed it to import_goi_sup**erf**req :////

Should be aaaal good now! I am going to test it!

**Comment by ChristofferFlensburg** [comment]
Ok, makes sense then! And yeah, this was SURELY the last bug in the code. 👍

**Comment by annaquaglieri16** [comment]
Sure, right?

This looks ok now!! Rownames and `chr` column are the same! 

![Screen Shot 2019-04-05 at 1 39 24 pm](https://user-images.githubusercontent.com/7087258/55600586-5f822e00-57a8-11e9-9171-0776c2579cd8.png)
