### ISSUE TITLE
clean up the INDELs output from VarDict

### ISSUE THREAD

**Issue by annaquaglieri16** [annaquaglieri16/varikondo#12]
This issue refers to the fact that sometimes an INDELs is called at Screening, for example, and then the same one is called at Cycle 1 but with a slightly different alternative allele. As things are now the same INDEL might look as different INDELs across a patient's time points but is instead the same one. 

I need to find a way to clean up the reporting of INDELs

**Comment by ChristofferFlensburg** [comment]
This is a very difficult problem. It's about indel variant standardisation, and I'm not sure it's a sovled problem... And even so, vardict might call variants that are not equivalent (but still based on the same actual variant) in different samples. Really would need something to go and cross check all the bams for specific variants. Not sure that there is such a method though... What about multiSNV? But yeah, this issue will require some work to solve I'm afraid. :/

**Comment by annaquaglieri16** [comment]
Yes, I know. The only thing I could think of as for now is manual curation :/
multiSNV seems to mainly work with somatic point mutations no?

**Comment by ChristofferFlensburg** [comment]
Yeah, manual curation, or write something that groups up similar-looking variants, but would be difficult to get right I think. For this package, I think you'll just have to trust the input I guess, in which case this is interpreted as two different variants. So something the user has to sort out before inserting into lineplots. Garbage in - garbage out principle.
