### ISSUE TITLE
If SampleName starts with number add an X - import_goi_superFreq.R

### ISSUE THREAD

**Issue by annaquaglieri16** [annaquaglieri16/varikondo#24]
Hey @ChristofferFlensburg, how do you do this in superFreq? When you read the metadata in, what's the command that you use to say: well if the sampleName starts with a number then I will add an X. Or does it do it automatically? 

Because now, when I read the stories in, all the sample names have an X in front of them while there is no X in the metadata. I could create a metadata with X before sample names but I was wondering how you handle this within superFreq. 

Thanks!

Anna

**Comment by ChristofferFlensburg** [comment]
It's beacause row/column/vector names are not allowed to start with numbers in R (because of... ¯\_(ツ)_/¯), and I use the sample names as column names in many cases. So when I import the sample names from the metadata file, I run them through `make.names`, which adds the X.

```
> make.names(1:4)
[1] "X1" "X2" "X3" "X4"
```

**Comment by annaquaglieri16** [comment]
Thanks!!
